version: "3.5"

services:
  # データベースサーバコンテナ
  # MySQL知らないのでPostgresqlを使っている
  # apiで対応出来るならRDBMはなんでもいい
  db:
    # net-tools等入れる必要がなければ公式イメージのままで大丈夫
    #image: postgres

    # 環境変数ではカバーできない部分を設定する場合コメントアウト
    build: ./db

    # Docker network上のホスト名
    hostname: database

    # 作成コンテナ名
    container_name: database-server

    # バックエンド用Docker network(internal)にのみ繋ぐ
    networks:
      - database-internal

    # 自動再起動
    restart: always

    # 名前付きVolumeにDBデータを割り当てて永続化させる
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
      #- ./db/ini:/docker-entrypoint-initdb.d

    # 環境変数設定
    # デフォルトパスワードはpostgresqlpwのleetspeak
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_PASSWORD: "p0579r35qlpw"


  # apiサーバ用コンテナ
  api:

    # ./api下のDockerfileからビルド
    build: ./api

    # Docker network上のホスト名
    hostname: api

    # 作成コンテナ名
    container_name: api-server

    # 内部ネットワークbackendとインターネットありのfrontendに接続
    networks:
      # 外側と繋げとかないとポートフォワード出来ないらしい
      # NAT自体がなくなるからだろうか
      - frontend
      - database-internal

    # host側127.0.0.1:80にコンテナ80ポートをバインド
    ports:
      - "80:80"

    # 環境変数
    environment:
      TZ: "Asia/Tokyo"

    depends_on:
      - db

  #haproxy:

    #build: ./haproxy-ssl

    #hostname: haproxy

    #container_name: haproxy-reverseproxy

    #networks:
    #  - frontend
    #  - database-internal

    #ports:
      #- "80:80"
    #  - "443:443"
    
    #volumes:

    #  - "/etc/letsencrypt:/etc/letsencrypt"
      #- "letsencrypt:/etc/letsencrypt"
      #- "letsencryptvar:/var/lib/letsencrypt"

  #letsencrypt:
    
    #image: certbot/certbot

    #volumes:
    
      #- "letsencrypt:/etc/letsencrypt"
      #- "letsencryptvar:/var/lib/letsencrypt"



# 利用するDocker networkの名前
networks:

  # フロントエンド側ネットワーク（インターネットアクセスあり）
  frontend:
    name: frontend
  #  internal: true

  # backend側内部ネットワーク
  # overlayではなくbridgeの外部アクセスを切ったもの
  database-internal:
    internal: true


# 永続化ディスクの名前
volumes:

  # postgresql用DBファイル
  postgres-db:

    # local driverはホスト側Volumeディレクトリをテキトーに使ってくれる
    # たぶん/var/lib/docker/volumes/docker-compose-$(VOLUME_NAME)/_data下
    driver: local

  # lets encrypt証明書
  letsencrypt:

    driver: local
    
    #external: true

  letsencryptvar:

    driver: local
    